### ISSUE TITLE
Unable to handle filenames other than the date

### ISSUE THREAD

**Issue by ignism** [Gruntfuggly/vscode-journal-view#1]
the journal consists of following folder structure:
```
Journal
    - #### (year)
        - ## (month)
            - ##.md (day, as file)
            - ## (day as folder)
                - title.md (created when a named note is created)
```

The viewer doesn't handle the named notes correctly. See the screenshot below:

<img width="312" alt="screen shot 2018-03-14 at 14 32 14" src="https://user-images.githubusercontent.com/2485645/37405279-8599f126-2794-11e8-9f6c-f0b9b47a566f.png">

For convenience the file explorer is shown above the journal viewer.
As you can see I opened planning.md, the viewer refers to this as `Invalid Date NaNth`

**Comment by Gruntfuggly** [comment]
Thanks for the report - I've never used the notes feature before, so I didn't take it into account.

**Comment by Gruntfuggly** [comment]
Please try the latest version.

**Comment by ignism** [comment]
Yep! It works now, thank you very much!
