### ISSUE TITLE
Extension overrides CMD+J keybinding

### ISSUE THREAD

**Issue by thiagodebastos** [Gruntfuggly/vscode-journal-view#12]
With this extension installed, I have no access to `CMD+J` as a keybinding. This is VSCode's default binding for toggling the panel.
With this extension installed, `CMD+J` starts a `chord` sequence and waits for the next chord, rather than toggling the panel.

Is this intentional? I can't find anything about it in the documentation, issues or the codebase after a quick skim.

**Comment by thiagodebastos** [comment]
My bad, I think this issue actually comes from `vscode-journal`.

**Comment by Gruntfuggly** [comment]
Yes - I checked, I don't set any keybindings. You can always remove the keybinding in the short term, but the author of the vscode-journal extension is normally pretty responsive.

**Comment by thiagodebastos** [comment]
Much appreciated @Gruntfuggly. FYI the issue has been reported and is being looked into in the in vscode-journal repo:

https://github.com/pajoma/vscode-journal/issues/47
