### ISSUE TITLE
Days are not sorted

### ISSUE THREAD

**Issue by tlang0** [Gruntfuggly/vscode-journal-view#13]
I'm not sure if this is only affects me, but the days in the journal view are not really in order:

![image](https://user-images.githubusercontent.com/518566/65693591-d839b700-e074-11e9-8d39-84a7df8c4b39.png)

I don't think this is the intended behavior?

OS: Windows 10 Pro
Region: Austria
Regional format: English (Austria)
Display language: English (United States)

**Comment by Gruntfuggly** [comment]
No, they should be ordered. Will investigate.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version which should sort properly. Please let me know if it works. 😄

**Comment by tlang0** [comment]
It works perfect now, thanks! :smiley:
