### ISSUE TITLE
duplicate items in the JOURNAL outline

### ISSUE THREAD

**Issue by TheKiteRunning** [Gruntfuggly/vscode-journal-view#2]
Hi, I really like this handy extension. 

Today I find a problem that some diaries are listed  in the JOURNAL outline twice, shown inside the yellow rectangle of the picture below. 

Thanks for your time!

![image](https://user-images.githubusercontent.com/24802332/40044847-370f71c8-585b-11e8-8059-9798efba4666.png)

**Comment by Gruntfuggly** [comment]
Hi - thanks for the report.

Is it reproducible? I have seen this sometimes before with a different extension - when the tree becomes corrupted. Does the refresh button fix it?

I have some plans to make some changes to the tree which may fix this (if it is the same issue I have seen before). I'll hopefully have a new release available shortly.

**Comment by TheKiteRunning** [comment]
Hi, thanks for your quick reply.

I don't know what's the meaning of "reproducible", however, I find the issue still there after I refresh the button or restart the computer.

Nice to hear your plans.

Best wishes

**Comment by Gruntfuggly** [comment]
I've made a few very small tweaks to the latest version which should hopefully fix the duplicates. Can you let me know if you see it again with the latest?

**Comment by TheKiteRunning** [comment]
@Gruntfuggly hi, I haven't noticed a version update, still 0.0.10, and i use vscode 1.240 insider.

This problem still exists.
![image](https://user-images.githubusercontent.com/24802332/40869529-656863ca-664f-11e8-9353-88603b5301a9.png)

**Comment by Gruntfuggly** [comment]
Does this happen straight away, or after using the filter or something like that?

**Comment by Gruntfuggly** [comment]
Also, approximately how many journal entries do you have?

**Comment by Gruntfuggly** [comment]
Hi - I've uploaded a new version (0.0.11) which should hopefully fix the issue. Please let me know if it works...

**Comment by TheKiteRunning** [comment]
Hi, sorry for my late reply, I should have checked github more frequently~ I noticed the upgrade, however, the issue remains yet~

I started taking notes with vsjournal from 28 April, and the situation is listed below:

| Month | dates with diaries |
| ----- | ---- |
| May   | 31   |
| June   | 8    |
| Total  | 39   |

| Month | dates with notes|
| ----- | ------ |
| May   | 13     |
| June   | 2      |
| Total  | 15     |

| Month | dates with duplicates|
| ----- | ---------- |
| May   | 4          |
| June   | 2          |
| Total  | 6          |

Taking notes is a necessary condition,but not a sufficient one for the issue.

| Date         | Notes? | Duplicate? |
| ------------ | ------ | ---------- |
| 2018/5/1     | 0      | 0          |
| **2018/5/2** | 1      | 1          |
| **2018/5/3** | 1      | 1          |
| 2018/5/4     | 0      | 0          |
| 2018/5/5     | 0      | 0          |
| **2018/5/6** | 1      | 1          |
| 2018/5/7     | 0      | 0          |
| 2018/5/8     | 0      | 0          |
| **2018/5/9** | 1      | 1          |
| 2018/5/10    | 0      | 0          |
| 2018/5/11    | 0      | 0          |
| 2018/5/12    | 1      | 0          |
| 2018/5/13    | 1      | 0          |
| 2018/5/14    | 1      | 0          |
| 2018/5/15    | 0      | 0          |
| 2018/5/16    | 1      | 0          |
| 2018/5/17    | 1      | 0          |
| 2018/5/18    | 1      | 0          |
| 2018/5/19    | 0      | 0          |
| 2018/5/20    | 0      | 0          |
| 2018/5/21    | 1      | 0          |
| 2018/5/22    | 0      | 0          |
| 2018/5/23    | 1      | 0          |
| 2018/5/24    | 1      | 0          |
| 2018/5/25    | 0      | 0          |
| 2018/5/26    | 0      | 0          |
| 2018/5/27    | 0      | 0          |
| 2018/5/28    | 0      | 0          |
| 2018/5/29    | 0      | 0          |
| 2018/5/30    | 0      | 0          |
| 2018/5/31    | 0      | 0          |
| 2018/6/1     | 0      | 0          |
| 2018/6/2     | 0      | 0          |
| 2018/6/3     | 0      | 0          |
| **2018/6/4** | 1      | 1          |
| **2018/6/5** | 1      | 1          |
| 2018/6/6     | 0      | 0          |
| 2018/6/7     | 0      | 0          |
| 2018/6/8     | 0      | 0          |

**Comment by Gruntfuggly** [comment]
Is this still happening with version 11?

**Comment by TheKiteRunning** [comment]
yes

![image](https://user-images.githubusercontent.com/24802332/41190087-0bc97e32-6c0b-11e8-851d-0930b0c82b94.png)
![image](https://user-images.githubusercontent.com/24802332/41190091-1bd5e89c-6c0b-11e8-9efa-1010a764e9a8.png)

**Comment by TheKiteRunning** [comment]
![image](https://user-images.githubusercontent.com/24802332/41197561-a4094710-6c95-11e8-8891-ac6f2882ad44.png)

**Comment by Gruntfuggly** [comment]
I don't think it is the same issue I thought it was - it looks from the screenshot like the tree is still behaving sensibly, just that it's duplicating some entries for some reason.
I'll upload a version with a debug log so hopefully I can understand what is happening.
One quick question - is it the same ones that get duplicated each time?

**Comment by TheKiteRunning** [comment]
sorry, I don't really understand the meaning of your question.

Actually, I haven't found any clear clues of the issue. What I know is the issue only occurs when I take notes that day. But there are also days when I take notes without duplicates.

the yellow square embraces the duplicates, and the red square embraces the days when I write diaries and take notes without duplicates.

I will try to uninstall and reinstall the extension a little later.（No use, the JOURNAL outline still contains duplicates）

![image](https://user-images.githubusercontent.com/24802332/41208208-5d359e60-6d53-11e8-8b57-5dd5951b24c9.png)

**Comment by Gruntfuggly** [comment]
Hi - I've been trying to investigate this, but haven't found anything at the moment.

Can you confirm a few things - 
- is your journal folder in the format `/Journal/YYYY/MM/DD` ?
- have you modified any of the configuration for the main journal extension?

**Comment by Gruntfuggly** [comment]
I've uploaded a new version which writes some logging to an output channel. If you go to the user preferences and set `vscode-journal-view.debug` to **true** and then restart, you should find a new output channel in the drop down list of the output panel. When you see the duplicates, can you copy the contents of the output channel please?

**Comment by TheKiteRunning** [comment]
Hi, 
- Q: is your journal folder in the format /Journal/YYYY/MM/DD ?
- A: Yes. Though I want to put my old diaries into this folder, I find it a little troublesome and have dropped the idea,
- Q: have you modified any of the configuration for the main journal extension?
- A: I have only configured the "journal.base": Diary/vsjournal
- Q: When you see the duplicates, can you copy the contents of the output channel please?
- A: I have set "vscode-journal-view.debug" to be true and restarted, but I found no ouput channel.

Besides, I find all of the duplicates occur in the dates before the 10th day, like May 02.

![image](https://user-images.githubusercontent.com/24802332/41764205-ff5a80a6-7632-11e8-9a44-761cec64abbb.png)

**Comment by Gruntfuggly** [comment]
That's it - it's the single digit days. I reproduced it here and added a fix. Please try the latest version.

**Comment by TheKiteRunning** [comment]
Thank you very much for your help so long! The issue has been fixed.

I should have noticed the single-digit problem earlier. 

Thanks again.

**Comment by Gruntfuggly** [comment]
No problem - my fault for not testing enough! 8-)
