### ISSUE TITLE
Save to iCloud

### ISSUE THREAD

**Issue by olgv** [Gruntfuggly/vscode-journal-view#21]
Hi there.

Is there any way one can point the `Journal:Base` towards an iCloud folder?
I made a Shortcut to a folder residing in iCloud, also tried adding the `~/Library/...` path to VS Code, but VS Code is unable to save the file in that location.

Any advice ? 
Thank you.

**Comment by Gruntfuggly** [comment]
Hi - I think you probably want to post this in the repo for the VSCode Journal extension itself (https://marketplace.visualstudio.com/items?itemName=Pajoma.vscode-journal). This extension is just an extra view for that extension.

**Comment by olgv** [comment]
Getting lost between repo waterfalls :)
Thank you
