### ISSUE TITLE
Top folder name in Tree displays Day + #

### ISSUE THREAD

**Issue by CDEguia** [Gruntfuggly/vscode-journal-view#3]
First item in the "tree view" shows the first entry date.
This should show the year.
![screenshot_20180710_150241](https://user-images.githubusercontent.com/16065545/42540342-e8264518-8452-11e8-8260-b91670995593.png)

**Comment by Gruntfuggly** [comment]
HI - can you provide some further information:

- does this happen all the time?
- have you changed any of the configuration?
- what platform are you running on?

Also, could you try setting `vscode-journal-view.debug` to **true** and restarting. If you then select the output panel (View -> Output), there should be an entry for **vscode-journal-view** in the drop down which should contain some logging from the extension. If you copy and paste in here, that would be really useful.

**Comment by CDEguia** [comment]
+ Does __not__ happen all the time
  + Un-installed, renamed the `Journal` folder and reinstalled and created a new entry
    + Tree view was fixed. :-) 
  + Reproduced the issue by copying the old `06` folder into the new `2018` folder.
    + Tree view issue occurred.
+ Setting changed to:
```
"journal.tpl-task-after": "## Tasks\n",
"journal.tpl-files-after": "## Notes\n",
"journal.tpl-memo-after": "## Memos\n",
"journal.tpl-entry": "# [Journal Entry for] dddd, MMMM Do YYYY[\n\n## Tasks\n\n## Notes\n\n## Memos\n]",
```
+ Running on current Fedora 28

Debug output starts __after__ issue appears :(

### OK... Narrowed it down to this.
Creating a `note` on the __first day__ of the __first month__ 
![screenshot_20180712_171834](https://user-images.githubusercontent.com/16065545/42666101-dbe41b12-85f7-11e8-8b07-f5947d9a2ac6.png)

**Comment by CDEguia** [comment]
I'd like to help, and found where the individual days are loaded into the Tree, but can't make out where/when the Year is loaded. I'm thinking it's in ```dataProvider.js```. If you could point me in the right direction I would like to take a shot at fixing it.

**Comment by Gruntfuggly** [comment]
Hi - the tree is built by going through each file path and recursively adding elements for each part of the path, all done in `dataProvider.add`. I expect the problem is due to something like the note being added before it's parent has been created. I'll also have a look at it this weekend.

**Comment by Gruntfuggly** [comment]
Found it - a stupid bit of logic which assumed that the element of the tree was a day when it could have been the year. Please try the latest version.

**Comment by CDEguia** [comment]
Cool... Fixed
