### ISSUE TITLE
Nothing found in Journal View

### ISSUE THREAD

**Issue by JamesEvolution** [Gruntfuggly/vscode-journal-view#4]
My journal entries are no longer showing in the Journal View:
![image](https://user-images.githubusercontent.com/33928277/46023465-9e8a4500-c0dc-11e8-9fe3-a6ce68fe4702.png)

This seems to have happened since a recent update to vscode-journal.

My **Journal: Base** setting in vs-code is: `C:/Users/james/Dropbox (Personal)/Journal`

That folder on my PC does contain the journal files and the journal extension is working correctly, using commands.

**Comment by Gruntfuggly** [comment]
Yeah me too. I'll investigate...

**Comment by Gruntfuggly** [comment]
Looks like there was a small change to remove the '.' from the extension used with journal entries.

Should be working again with the latest version...

**Comment by JamesEvolution** [comment]
Working great thanks!
