### ISSUE TITLE
Journal view displays "Nothing Found" on macOS 10.14

### ISSUE THREAD

**Issue by BillKracke** [Gruntfuggly/vscode-journal-view#5]
This feels like a duplicate of #4 , but my journal view is only displaying "Nothing found"

I have moved my journal folder to another location (~/Dropbox/log), but that appears to be working correctly.

Additionally, the "Today" button at the top of the view opens the correct file.

VS Code is at version 1.28.1

**Comment by Gruntfuggly** [comment]
Can you enable the debug channel in the output view using `"vscode-journal-view.debug": true"` and see if anything is shown in it?

The today button works because it calls the journal extension directly.

**Comment by Gruntfuggly** [comment]
Ah - I think I know what the problem is. The journal extension is able to handle the expansion of the '~' but this extension can't.

Try setting `journal.base` to the absolute path to your folder.

**Comment by BillKracke** [comment]
'~' in path was the issue ... I had used the home path variable, thinking that might avoid the issue, but the absolute path works perfectly. Thank you.

**Comment by Gruntfuggly** [comment]
I'll update the extension so that it uses the same method.

**Comment by kenlefeb** [comment]
I'm seeing this problem, too, but I am already using an absolute path in my journal.base.

I turned on diagnostics but I'm not really seeing anything in the logs. The journal-view log just shows words like "Rebuild", "Clear", etc., but no errors.

I am setting up a new machine, today, so I have the latest versions of everything. Do you have any ideas for me to troubleshoot this?

Thanks!

**Comment by Gruntfuggly** [comment]
Can you give me some more information about your set up - what OS and what is `journal.base` set to? I'm assuming that everything works OK with the journal extension itself?
