### ISSUE TITLE
Month names wrong

### ISSUE THREAD

**Issue by Flagrare** [Gruntfuggly/vscode-journal-view#8]
Hi, I am currently using the last version (v 0.0.20), but the bug solved in #6 still persists. December is showing as November.
![image](https://user-images.githubusercontent.com/16652604/49705490-a51d5880-fc05-11e8-980d-cf4601e2ca34.png)
Btw, such a great extension. Thanks for it!

**Comment by wari** [comment]
Just used this, 2019/01 is displayed as December

**Comment by wari** [comment]
Example of what this looks like

![image](https://user-images.githubusercontent.com/525422/50594277-e50aef00-0ed6-11e9-805c-bb2b0138c964.png)

**Comment by Gruntfuggly** [comment]
Argh! Dates are hard!

**Comment by Gruntfuggly** [comment]
Could you copy the contents of the vscode-journal-view output window for me please?

**Comment by wari** [comment]
What is the output window? Not sure what you mean. But clicking on the Calendar button, for me will bring up the correct file (say 2019/01/03.md), just that the tree-view is showing the wrong month.

**Comment by Gruntfuggly** [comment]
If you go to the settings for Journal View, you should find a debug option. If you select that and restart you should find a new output view (View->Output) in the drop down control called `vscode-journal-view`. If you select that you should find some diagnostic information from when the tree was built. If you can copy and paste it here it would be very useful.

**Comment by wari** [comment]
Here it is.

```
clear
add: {"type":"entry","name":"28.md","file":"/Users/wwahab/Journal/2018/11/28.md","id":1791983,"icon":"journal-entry","date":"2018-11-27T16:00:00.000Z","clickable":true,"visible":true,"displayName":"Wednesday 28th"}
add: {"type":"entry","name":"11.md","file":"/Users/wwahab/Journal/2018/12/11.md","id":1579640,"icon":"journal-entry","date":"2018-12-10T16:00:00.000Z","clickable":true,"visible":true,"displayName":"Tuesday 11th"}
add: {"type":"entry","name":"01.md","file":"/Users/wwahab/Journal/2019/01/01.md","id":1795894,"icon":"journal-entry","date":"2018-12-31T16:00:00.000Z","clickable":true,"visible":true,"displayName":"Tuesday 1st"}
add: {"type":"note","name":"For_the_meeting_tonight.md","file":"/Users/wwahab/Journal/2019/01/02/For_the_meeting_tonight.md","id":1383921,"icon":"notes","date":"2019-01-01T16:00:00.000Z","clickable":true,"visible":true,"displayName":"For the meeting tonight"}
add: {"type":"note","name":"On-call.md","file":"/Users/wwahab/Journal/2019/01/03/On-call.md","id":1223799,"icon":"notes","date":"2019-01-02T16:00:00.000Z","clickable":true,"visible":true,"displayName":"On-call"}
add: {"type":"note","name":"freenode.md","file":"/Users/wwahab/Journal/2019/01/03/freenode.md","id":1855367,"icon":"notes","date":"2019-01-02T16:00:00.000Z","clickable":true,"visible":true,"displayName":"freenode"}
add: {"type":"entry","name":"04.md","file":"/Users/wwahab/Journal/2019/01/04.md","id":1885267,"icon":"journal-entry","date":"2019-01-03T16:00:00.000Z","clickable":true,"visible":true,"displayName":"Friday 4th"}
add: {"type":"note","name":"One-on-One.md","file":"/Users/wwahab/Journal/2019/01/08/One-on-One.md","id":1503821,"icon":"notes","date":"2019-01-07T16:00:00.000Z","clickable":true,"visible":true,"displayName":"One-on-One"}
add: {"type":"entry","name":"09.md","file":"/Users/wwahab/Journal/2019/01/09.md","id":1034222,"icon":"journal-entry","date":"2019-01-08T16:00:00.000Z","clickable":true,"visible":true,"displayName":"Wednesday 9th"}
add: {"type":"entry","name":"10.md","file":"/Users/wwahab/Journal/2019/01/10.md","id":1689624,"icon":"journal-entry","date":"2019-01-09T16:00:00.000Z","clickable":true,"visible":true,"displayName":"Thursday 10th"}
refresh
```

**Comment by Gruntfuggly** [comment]
Thanks - I can't reproduce it though.

Do you mind doing a bit of hacking for me? Please open:

`.vscode/extensions/Gruntfuggly.vscode-journal-view-0.0.20/dataProvider.js`

and add the line following line at line 37:

```
    var date = new Date( 1970, parseInt( number ) - 1, 1 );
    console.log( "getMonth for " + number + " -> date: " + date.toISOString() ); // <-- This
    return date.toLocaleString( vscode.env.language, { month: "long" } );
```

If you then do Help -> Toggle Developer Tools and let me know what is shown in the console window that would be great.

**Comment by wari** [comment]
I think I know what the problem is!

My timezone is +0800, and I believe yours is somewhere in the negative range. 1st of Jan, 00:00 for me is still December 2018 in UTC.

I have not done the changes, but I'll do it later in the office to test, though I suspect, the above problem as described is the issue here.

**Comment by wari** [comment]
Yup, I'm correct, the date is 8 hours behind showing last month's name

```
add: {"type":"note","name":"DOI2696.md","file":"/Users/wwahab/Journal/2019/01/04/DOI2696.md","id":1218781,"icon":"notes","date":"2019-01-03T16:00:00.000Z","clickable":true,"visible":true,"displayName":"DOI2696"}
```

**Comment by wari** [comment]
```
[Extension Host] getMonth for 01 -> date: 1969-12-31T16:00:00.000Z 
```

**Comment by wari** [comment]
Created pull request #9 for a theoretical fix.

**Comment by wari** [comment]
Just FYI, what I see with the `userDate`:

```
console.log( "getMonth for " + number + " -> userDate: " + userDate.toISOString() + " offset: " + date.getTimezoneOffset());
	
[Extension Host] getMonth for 01 -> userDate: 1970-01-01T00:00:00.000Z offset: -480
```

**Comment by Gruntfuggly** [comment]
Thanks - I'll merge your changes as it will definitely be an improvement, even considering the edge cases you've identified.

**Comment by wari** [comment]
I believe this would also be fixed if you do something like:

```javascript
var date = new Date( 1970, parseInt( number ) - 1, 15 );
```

**Comment by samvrlewis** [comment]
Maybe a related issue, but the days listed in the journal view are off by one for me. For example, the journal listed as 'Friday the 11th' is listed in the journal view as Thursday the 11th:

![screenshot from 2019-01-11 10-59-08](https://user-images.githubusercontent.com/3880246/51004743-1bf49b00-1590-11e9-81b1-211ce6e6b81d.png)

Output:

```
clear
add: {"type":"entry","name":"10.md","file":"/home/sam/sam-stuff/journal/2019/01/10.md","id":1915089,"icon":"journal-entry","date":"2019-01-09T13:00:00.000Z","clickable":true,"visible":true,"displayName":"Wednesday 10th"}
add: {"type":"entry","name":"11.md","file":"/home/sam/sam-stuff/journal/2019/01/11.md","id":1885298,"icon":"journal-entry","date":"2019-01-10T13:00:00.000Z","clickable":true,"visible":true,"displayName":"Thursday 11th"}
refresh
```

Thanks for the great extension!!

**Comment by marciopamplona** [comment]
Using the version 0.0.21, same problem here.

@wari , your solution fixed it.

**`dataProvider.js`**
`36: var date = new Date( 1970, parseInt( number ) - 1, 15 );`

**Comment by dbrionesendpoint** [comment]
This is NOT fixed, I'm in EST -5 and my Journal-View display is December even though the folder is correctly named 01 in January. running 0.0.21

**Comment by Gruntfuggly** [comment]
I've just published an update with the change.
